# Generated by Django 2.1.7 on 2019-02-19 16:08

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('credential', models.CharField(max_length=150, null=True)),
                ('avatar', models.ImageField(default='', upload_to=pages.models.Testimonial.get_dp_path, verbose_name='Profile Picture')),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
                'verbose_name': 'Testimonial',
            },
        ),
    ]
