# Generated by Django 2.1.7 on 2019-02-13 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('gsoc', '0001_initial'),
        ('activity', '0002_auto_20190213_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsoc',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GSoCOrganisation', to='members.Organization'),
        ),
        migrations.AddField(
            model_name='gsoc',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GSoCProject', to='activity.Project'),
        ),
        migrations.AddField(
            model_name='gsoc',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='GSoCTopics', to='members.Skill'),
        ),
    ]
