# Generated by Django 2.1.7 on 2019-02-19 16:08

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField()),
                ('session_end', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Attendance',
                'verbose_name': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='EducationalQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Educational Qualifications',
                'verbose_name': 'Educational Qualification',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Groups',
                'verbose_name': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, help_text='YYYY-MM-DD', null=True, verbose_name='From')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, help_text='YYYY-MM-DD', null=True, verbose_name='To')),
                ('type', models.CharField(choices=[('M', 'Health'), ('F', 'Family/Home'), ('T', 'Tiredness'), ('A', 'Academics'), ('D', 'Duty')], default='T', max_length=2, verbose_name='Type')),
                ('reason', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Leave Records',
                'verbose_name': 'Leave Record',
            },
        ),
        migrations.CreateModel(
            name='MentorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Mentor Groups',
                'verbose_name': 'Mentor Group',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, default='', null=True, upload_to=members.models.Organization.get_icon_path, verbose_name='Logo/Icon')),
            ],
        ),
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('icon', models.CharField(max_length=25, null=True, verbose_name='Icon Class')),
                ('color', models.CharField(help_text='hexcode with #', max_length=10, null=True, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=25, null=True)),
                ('batch', models.IntegerField(blank=True, help_text='Year of Admission', null=True)),
                ('avatar', models.ImageField(default='', upload_to=members.models.Profile.get_dp_path, verbose_name='Profile Picture')),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('birthday', models.DateField(blank=True, help_text='YYYY-MM-DD', null=True)),
                ('tagline', models.CharField(blank=True, max_length=80, null=True)),
                ('about', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('typing_speed', models.IntegerField(blank=True, null=True)),
                ('system_no', models.IntegerField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=members.models.Profile.get_resume_path, verbose_name='Attach Resume')),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Responsibilities',
                'verbose_name': 'Responsibility',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('T', 'Technical'), ('A', 'Arts'), ('S', 'Social'), ('P', 'Sports'), ('O', 'Others')], default='O', max_length=1)),
                ('icon', models.ImageField(blank=True, default='', null=True, upload_to=members.models.Skill.get_icon_path, verbose_name='Icon')),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=150, verbose_name='Profile URL')),
            ],
            options={
                'verbose_name_plural': 'Social Profile Links',
                'verbose_name': 'Social Profile Link',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('about', ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True)),
                ('members', models.ManyToManyField(related_name='Team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'verbose_name': 'Team',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='members.Organization', verbose_name='Organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Profile')),
                ('projects', models.ManyToManyField(blank=True, to='activity.Project')),
            ],
            options={
                'verbose_name_plural': 'Work Experiences',
                'verbose_name': 'Work Experience',
            },
        ),
    ]
